version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    container_name: flask_app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - qdrant
      - ollama
    networks:
      - net

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  net:
    driver: bridge
